### ISSUE TITLE
When search a contract with type of stake,throw an error

### ISSUE THREAD

**Issue by fuhuimin** [pooltogether/pooltogether-community-ui#38]
PoolData.jsx:23 Error fetching pool addresses for prize pool with address: 0xC5445655BB57C645Cc9204c56b65A1c777543fdd: execution reverted. (maybe wrong Ethereum network or your IP is being rate-limited?)

**Comment by chuckbergeron** [comment]
hey @fuhuimin - I'm not seeing that address, are you sure that's where the pool is deployed? On both rinkeby and mainnet it looks like there is nothing there:
https://etherscan.io/address/0xC5445655BB57C645Cc9204c56b65A1c777543fdd
https://rinkeby.etherscan.io/address/0xC5445655BB57C645Cc9204c56b65A1c777543fdd
