### ISSUE TITLE
UI does not update after approving contract spending with zero token balance

### ISSUE THREAD

**Issue by Jay-Way** [pooltogether/pooltogether-community-ui#45]
I just found a (minor) issue with the PoolTogether UI, I am not quite sure if this here is the correct repo, but here is the issue:

**Summary**:

When visiting https://app.pooltogether.com/pools/PT-cDAI/deposit and approving DAI you can approve it and after the tx confirmed the UI tells you that it is still unapproved. That only seems to happen when you have 0 DAI in your wallet.

**Steps to reproduce**:

1. Go to https://app.pooltogether.com/pools/PT-cDAI/deposit
2. Enter 0 in the 'Ticket amount' field, click continue
3. Approve DAI via Metamask etc.
4. Now you see that 'Allow DAI' is still clickable, even though the connected wallet has already approved it. That only happens when you enter 0 DAI in the 'Ticket amount' field (Page reload is not helping)

I think users (Like I just did) want to approve DAI (or different tokens) while not actually holding any DAI/Token in the wallet (yet). This leads to confusion and probably double-approving without the UI telling you that it worked on the first time.

**Comment by chuckbergeron** [comment]
@Jay-Way Is this still happening for you?

**Comment by chuckbergeron** [comment]
This is fixed in master and slated for release to production on Monday 👍  thanks for reporting!
