### ISSUE TITLE
Get community pools on Polygon

### ISSUE THREAD

**Issue by rdp3** [pooltogether/pooltogether-community-ui#79]
https://community.pooltogether.com/pools/matic/0x9e299cf900a81b55024398ff2cdb1c9c0fcec902/home

Pool not displaying on https://community.pooltogether.com/ when on Polygon Mainnet

**Comment by chuckbergeron** [comment]
Looks like this has been added to `PRIZE_POOL_LIST_FALLBACK` constant in `useAllCreatedPrizePools` - should be good to go
