### ISSUE TITLE
Error: "networkId" is required

### ISSUE THREAD

**Issue by Araton95** [pooltogether/pooltogether-community-ui#91]
After all steps, the app not builds, with an error `"networkId" is required`.

I guess it comes from `@pooltogether/bnc-onboard` package but could not find any solution... 

Any idea how it can be solved?

<img width="1502" alt="Screenshot 2021-07-06 at 14 17 33" src="https://user-images.githubusercontent.com/16293599/124591684-407e1500-de65-11eb-8635-595dafdf9131.png">

**Comment by Araton95** [comment]
Solved. Installed `dotenv` and moved environment variables there.

**Comment by ss5nathan** [comment]
Having a similar issue, can you provide more details on your solution?
